language: php
dist: trusty
sudo: false

cache:
    directories:
    - vendor
    - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
    fast_finish: true
    allow_failures:
    - php: nightly

addons:
    apt:
        packages:
        - libffi-dev

notifications:
    email: false
    irc:
      channels:
        - "irc.iiens.net#Clicky"
      on_success: change
      on_failure: always

before_script:
    - rm -rf vendor/
    - rm composer.lock
    - composer self-update -n
    - composer install -n

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs
